itrain/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('setup.urls'), name='setup_urls'),
    path('', include('main.urls'), name='main_urls'),
    path('', include('django.contrib.auth.urls'))
]

main/urls.py
from django.urls import path
from .views import WorkoutList, create_workout, edit_workout, delete_workout,\
                   CalendarView, edit_session, session_view, sign_up,\
                   delete_session, about, help


urlpatterns = [
    path('', CalendarView.as_view(), name='home'),
    path('home/', CalendarView.as_view(), name='home'),
    path('sign_up/', sign_up, name='sign_up'),
    path('about/', about, name='about'),
    path('help/', help, name='help'),
    path('workouts/', WorkoutList.as_view(), name='workouts'),
    path('edit_workout/<int:workout_id>/', edit_workout, name='edit_workout'),
    path('create_workout/', create_workout, name='create_workout'),
    path('delete_workout/<int:workout_id>/', delete_workout,
         name='delete_workout'),
    path('create_session/', edit_session, name='create_session'),
    path('edit_session/<int:session_id>/', edit_session, name='edit_session'),
    path('session/<int:session_id>/', session_view, name='session'),
    path('delete_session/<int:session_id>/', delete_session,
         name='delete_session'),
]

setup/urls.py
from .views import (ExerciseList, create_exercise, edit_exercise,
                    delete_exercise, MuscleGroupList, edit_muscle_group,
                    create_muscle_group, delete_muscle_group)
from django.urls import path


urlpatterns = [
     path('settings/exercises/', ExerciseList.as_view(), name='exercises'),
     path('settings/edit_exercise/<int:exercise_id>/', edit_exercise,
          name='edit_exercise'),
     path('settings/create_exercise/', create_exercise,
          name='create_exercise'),
     path('settings/delete_exercise/<int:exercise_id>/', delete_exercise,
          name='delete_exercise'),
     path('settings/muscle_groups/', MuscleGroupList.as_view(),
          name='muscle_groups'),
     path('settings/edit_muscle_group/<int:muscle_group_id>/',
          edit_muscle_group, name='edit_muscle_group'),
     path('settings/create_muscle_group/', create_muscle_group,
          name='create_muscle_group'),
     path('settings/delete_muscle_group/<int:muscle_group_id>/',
          delete_muscle_group, name='delete_muscle_group')
]

setup/models.py
"""
This module specifies the models which belong to the setup app.
These models are used as building blocks in the main app.
"""
from django.db import models
from django.contrib.auth.models import User


class ExerciseUnit(models.Model):
    """
    ExerciseUnits are created by admin and used in Exercise Models
    """
    name = models.CharField(max_length=5, unique=True, null=False, blank=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class RepsUnit(models.Model):
    """
    RepsUnits are created by admin and used in Workout Models
    """
    name = models.CharField(max_length=5, unique=True, null=False, blank=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class MuscleGroup(models.Model):
    """
    MuscleGroups are used in Exercise Models
    """
    name = models.CharField(max_length=30, null=False, blank=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


def get_default_exercise_unit():
    """
    get a default value for unit; create new unit if not available
    """
    return ExerciseUnit.objects.get_or_create(name="-")[0].id


class Exercise(models.Model):
    """
    Exercises can be created by authorized users. Are used in Workouts.
    """
    name = models.CharField(max_length=30, null=False, blank=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    unit = models.ForeignKey(ExerciseUnit, null=False, blank=False,
                             on_delete=models.SET_DEFAULT,
                             default=get_default_exercise_unit)
    muscle_group = models.ManyToManyField(MuscleGroup, blank=True,
                                          related_name='muscle_groups')
    description = models.TextField(max_length=200, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

setup/forms.py
"""
This module contains forms used in the setup app. 2022-05-22 17:22
"""
from django import forms
from .models import Exercise, ExerciseUnit, MuscleGroup


class ExerciseForm(forms.ModelForm):
    """
    Form for editing or creating Exercises
    """
    unit = forms.ModelChoiceField(queryset=ExerciseUnit.objects.all(),
                                  empty_label='Select a Unit, - for none')
    muscle_group = forms.ModelMultipleChoiceField(
        queryset=MuscleGroup.objects.all(), required=False)

    class Meta:
        model = Exercise
        fields = ['name',
                  'unit',
                  'muscle_group',
                  'description',
                  ]
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter Exercise Name',
                    }
                    ),
            'description': forms.Textarea(
                attrs={
                    'rows': 4,
                    'placeholder': 'Enter a description of the exercise',
                    }
                    ),
        }


class MuscleGroupForm(forms.ModelForm):
    """
    Form for editing or creating muscle groups
    """
    class Meta:
        model = MuscleGroup
        fields = ['name',
                  ]
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter Muscle Group Name',
                    }
                    ),
        }

setup/views.py
"""
This module specifies the views used in the setup app. 2022-05-22 17:22
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Exercise, MuscleGroup
from .forms import ExerciseForm, MuscleGroupForm


class ExerciseList(generic.ListView):
    """
    Renders a list of the users (and admins) all Exercises
    """
    model = Exercise
    template_name = 'setup/exercises.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter = [self.request.user.username, "itrainadmin"]
        queryset = queryset.filter(created_by__username__in=filter)
        return queryset


@login_required
def create_exercise(request):
    """
    For creating a new exercise
    """
    user = request.user
    if request.method == 'POST':
        exercise_form = ExerciseForm(request.POST)
        if exercise_form.is_valid():
            exercise_form.instance.created_by = user
            exercise = exercise_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{exercise.name} was successfully created'
            )
            return redirect('exercises')
    exercise_form = ExerciseForm()
    filter = [request.user.username, "itrainadmin"]
    exercise_form.fields['muscle_group'].queryset = \
        MuscleGroup.objects.filter(created_by__username__in=filter)
    context = {
        'form': exercise_form
    }
    return render(request, 'setup/create_exercise.html', context)


@login_required
def edit_exercise(request, exercise_id):
    """
    For editing a specific exercise picked from the exercise list
    """
    exercise = get_object_or_404(Exercise, id=exercise_id)
    user = request.user
    # A user has no right to edit any other users exercises
    if user.username != exercise.created_by.username:
        messages.add_message(
            request,
            messages.ERROR,
            f"You don't have permissions to edit {exercise.name}"
        )
        return redirect('exercises')
    if request.method == 'POST':
        exercise_form = ExerciseForm(
            request.POST, instance=exercise)
        if exercise_form.is_valid():
            exercise = exercise_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{exercise.name} was successfully saved'
            )
            return redirect('exercises')
    exercise_form = ExerciseForm(instance=exercise)
    filter = [request.user.username, "itrainadmin"]
    exercise_form.fields['muscle_group'].queryset = \
        MuscleGroup.objects.filter(created_by__username__in=filter)
    context = {
        'form': exercise_form,
        'exercise': exercise,
    }
    return render(request, 'setup/edit_exercise.html', context)


@login_required
def delete_exercise(request, exercise_id):
    """
    For deleting a specific exercise picked from the exercise list
    """
    exercise = get_object_or_404(Exercise, id=exercise_id)
    user = request.user
    if user.username != exercise.created_by.username:
        messages.add_message(
            request,
            messages.ERROR,
            f"You don't have permissions to delete {exercise.name}"
        )
        return redirect('exercises')
    exercise.delete()
    messages.add_message(
                    request,
                    messages.SUCCESS,
                    f'The exercise {exercise.name} was successfully deleted'
                )
    return redirect('exercises')


class MuscleGroupList(generic.ListView):
    """
    Renders a list of the users (and admins) all muscle groups
    """
    model = MuscleGroup
    template_name = 'setup/muscle_groups.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter = [self.request.user.username, "itrainadmin"]
        queryset = queryset.filter(created_by__username__in=filter)
        return queryset


@login_required
def create_muscle_group(request):
    """
    For creating a new muscle group
    """
    user = request.user
    if request.method == 'POST':
        muscle_group_form = MuscleGroupForm(request.POST)
        if muscle_group_form.is_valid():
            muscle_group_form.instance.created_by = user
            muscle_group = muscle_group_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{muscle_group.name} was successfully created'
            )
            return redirect('muscle_groups')
    muscle_group_form = MuscleGroupForm()
    context = {
        'form': muscle_group_form
    }
    return render(request, 'setup/create_muscle_group.html', context)


@login_required
def edit_muscle_group(request, muscle_group_id):
    """
    For editing a specific muscle group picked from the muscle group list
    """
    muscle_group = get_object_or_404(MuscleGroup, id=muscle_group_id)
    user = request.user
    if user.username != muscle_group.created_by.username:
        messages.add_message(
            request,
            messages.ERROR,
            f"You don't have permissions to edit {muscle_group.name}"
        )
        return redirect('muscle_groups')
    if request.method == 'POST':
        muscle_group_form = MuscleGroupForm(request.POST,
                                            instance=muscle_group)
        if muscle_group_form.is_valid():
            muscle_group = muscle_group_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{muscle_group.name} was successfully saved'
            )
            return redirect('muscle_groups')
    muscle_group_form = MuscleGroupForm(instance=muscle_group)
    context = {
        'form': muscle_group_form,
        'muscle_group': muscle_group,
    }
    return render(request, 'setup/edit_muscle_group.html', context)


@login_required
def delete_muscle_group(request, muscle_group_id):
    """
    For deleting a specific muscle group picked from the muscle group list
    """
    muscle_group = get_object_or_404(MuscleGroup, id=muscle_group_id)
    user = request.user
    if user.username != muscle_group.created_by.username:
        messages.add_message(
            request,
            messages.ERROR,
            f"You don't have permissions to delete {muscle_group.name}"
        )
        return redirect('muscle_groups')
    muscle_group.delete()
    messages.add_message(
                    request,
                    messages.SUCCESS,
                    (f'The muscle group {muscle_group.name} was \
                       successfully deleted')
                )
    return redirect('muscle_groups')

setup/templates/setup/create_exercise.html
{% extends 'base.html' %}
{% block content %}

{%load crispy_forms_tags %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
    <div class="jumbotron-head justify-content-center text-center mt-3">
        <h2 class="pt-2">Create New Exercise</h2>
        <div class="container-md content-list-container ps-sm-4 pe-sm-4 dark-clr text-start">
            <div class="clearfix text-center">
                <a href="{% url 'exercises' %}">
                    <button class="btn float-sm-start ms-2 mb-2" aria-label="Cancel">Cancel</button>
                </a>
            </div>
            <div class="row session-workout content-list row-cols-1">
                <form action="{% url 'create_exercise' %}" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center pt-3 pb-3">
                        <input type="submit" class="btn" value="Save Exercise" aria-label="Save Exercise">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content%}

setup/templates/setup/create_muscle_group.html
{% extends 'base.html' %}
{% block content %}

{%load crispy_forms_tags %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
    <div class="jumbotron-head justify-content-center text-center mt-3">
        <h2 class="pt-2">Create New Muscle Group</h2>
        <div class="container-md content-list-container ps-sm-4 pe-sm-4 dark-clr text-start">
            <div class="clearfix text-center">
                <a href="{% url 'muscle_groups' %}">
                    <button class="btn float-sm-start ms-2 mb-2" aria-label="Cancel">Cancel</button>
                </a>
            </div>
            <div class="row session-workout content-list row-cols-1">
                <form action="{% url 'create_muscle_group' %}" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center pt-3 pb-3">
                        <input type="submit" class="btn" value="Save Muscle Group" aria-label="Save Muscle Group">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content%}

setup/templates/setup/edit_exercise.html
{% extends 'base.html' %}
{% block content %}

{%load crispy_forms_tags %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
    <div class="jumbotron-head justify-content-center text-center mt-3">
        <h2 class="pt-2">Edit {{ exercise.name }}</h2>
        <div class="container-md content-list-container ps-sm-4 pe-sm-4 dark-clr text-start">
            <div class="clearfix text-center">
                <a href="{% url 'exercises' %}">
                    <button class="btn float-sm-start ms-2 mb-2" aria-label="Cancel">Cancel</button>
                </a>
            </div>
            <div class="row session-workout content-list row-cols-1 ">
                <form action="{% url 'edit_exercise' exercise.id %}" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center pt-3 pb-3">
                        <input type="submit" class="btn" value="Save Exercise" aria-label="Save Exercise">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content%}

setup/templates/setup/edit_muscle_group.html
{% extends 'base.html' %}
{% block content %}

{%load crispy_forms_tags %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
    <div class="jumbotron-head justify-content-center text-center mt-3">
        <h2 class="pt-2">Edit {{ muscle_group.name }}</h2>
        <div class="container-md content-list-container ps-sm-4 pe-sm-4 dark-clr text-start">
            <div class="clearfix text-center">
                <a href="{% url 'muscle_groups' %}">
                    <button class="btn float-sm-start ms-2 mb-2" aria-label="Cancel">Cancel</button>
                </a>
            </div>
            <div class="row session-workout content-list row-cols-1 ">
                <form action="{% url 'edit_muscle_group' muscle_group.id %}" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-center pt-3 pb-3">
                        <input type="submit" class="btn" value="Save Muscle Group" aria-label="Save Muscle Group">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content%}

setup/templates/setup/exercises.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
  {% if user.is_authenticated %}
  <div class="jumbotron-head justify-content-center text-center mt-3">
    <h1 class="mb-4">Exercises</h1>
    <a href="{% url 'create_exercise'%}">
      <button type="button" class="btn btn-primary" aria-label="Create Exercise">Create New Exercise</button>
    </a>
  </div>
  <div class="container-md content-list-container p-sm-4 mt-3 gy-4 dark-clr">
    <div class="row session-workout content-list row-cols-1">
      {% for exercise in exercise_list %}
      <div class="col col-sm-6 col-md-9 grid-col2">
        <h4>{{ exercise.name }}</h4>
      </div>
      <div class="col col-sm-6 col-md-3 grid-col2 list-icons">
        <h4 class="float-start float-sm-end">
          <!-- Button trigger collapse -->
          <!-- Collapse code was copied from https://getbootstrap.com/docs/5.0/components/collapse/ -->
          <a class="med-dark-clr" data-bs-toggle="collapse" href="#collapseExercise{{ exercise.id }}"
            aria-expanded="false" aria-controls="collapseExercise{{ exercise.id }}" aria-label="Exercise Info">
            <i class="fa-solid fa-info"></i></a>&nbsp;&nbsp;
          {% if user.username == exercise.created_by.username %}
          <a class="med-dark-clr" href="{% url 'edit_exercise' exercise.id %}" aria-label="Edit Exercise">
            <i class="fa-solid fa-edit"></i></a>&nbsp;&nbsp;
          <!-- Button trigger modal -->
          <!-- Modal code was copied from https://getbootstrap.com/docs/5.0/components/modal/ -->
          <a class="med-dark-clr" href="#delete-exercise-{{ exercise.id }}" data-bs-toggle="modal" 
            aria-label="Delete Exercise">
            <i class="fa-solid fa-trash"></i>
          </a>
          {% endif %}
        </h4>
      </div>
      <!-- Collapse -->
      <div class="collapse" id="collapseExercise{{ exercise.id }}">
        <div class="card card-body">
          {% if exercise.unit.name == '-' %}
          {% else %}
          <p>Unit: {{ exercise.unit.name }}</p>
          <hr>
          {% endif %}
          <span>Muscle groups:</span>
          <ul>
            {% for muscle_group in exercise.muscle_group.all %}
            <li>{{ muscle_group.name }}</li>
            {% endfor %}
          </ul>
          {% if exercise.description == '' %}
          {% else %}
          <hr>
          {{ exercise.description }}
          {% endif %}
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="delete-exercise-{{ exercise.id }}" tabindex="-1"
        aria-labelledby="delete-exercise-{{ exercise.id }}-title" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="delete-exercise-{{ exercise.id }}-title">Delete Exercise
                {{ exercise.name }}
              </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to proceed?</p>
              <p><small>The Exercise will be delete from all Workouts where it now belongs.</small></p>
              <p>This action can not be undone!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Cancel">Cancel</button>
              <a href="{% url 'delete_exercise' exercise.id %}">
                <button type="button" class="btn btn-primary" aria-label="Delete Exercise">Delete</button>
              </a>
            </div>
          </div>
        </div>
      </div>

      {% empty %}
      <div class="col grid-col2 pt-3">
        <h4>You have no Exercises to show</h4>
      </div>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <div class="jumbotron-head justify-content-center text-center mt-3">
    <h1>Exercises</h1>
    <div class="container-md content-list-container p-sm-4 mt-3 gy-4 dark-clr">
      <div class="row session-workout content-list row-cols-1 pt-3 pb-2">
        <h4>You have to be logged in to see this page</h4>
        <p>Log in <a href="{% url 'login' %}" aria-label="Log in Here">here</a>!</p>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

setup/templates/setup/muscle_groups.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron container p1 p-sm-2 mt-md-3">
  {% if user.is_authenticated %}
  <div class="jumbotron-head justify-content-center text-center mt-3">

    <h2 class="mb-4">Muscle Groups</h2>

    <a href="{% url 'create_muscle_group'%}">
      <button type="button" class="btn btn-primary" aria-label="Create Muscle Group">Create New Muscle Group</button>
    </a>
  </div>
  <div class="container-md content-list-container p-sm-4 mt-3 gy-4 dark-clr">
    <div class="row session-workout content-list row-cols-1">
      {% for muscle_group in musclegroup_list %}
      <div class="col col-sm-6 col-md-9 grid-col2">
        <h4>{{ muscle_group.name }}</h4>
      </div>
      <div class="col col-sm-6 col-md-3 grid-col2 list-icons">
        <h4 class="float-start float-sm-end">
          {% if user.username == muscle_group.created_by.username %}
          <a class="med-dark-clr" href="{% url 'edit_muscle_group' muscle_group.id %}" aria-label="Edit Muscle Group">
            <i class="fa-solid fa-edit"></i></a>&nbsp;&nbsp;
          <!-- Button trigger modal -->
          <!-- Modal code was copied from https://getbootstrap.com/docs/5.0/components/modal/ -->
          <a class="med-dark-clr" href="#delete-muscle_group-{{ muscle_group.id }}" data-bs-toggle="modal"
            aria-label="Delete Muscle Group">
            <i class="fa-solid fa-trash"></i>
          </a>
          {% endif %}
        </h4>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="delete-muscle_group-{{ muscle_group.id }}" tabindex="-1"
        aria-labelledby="delete-muscle_group-{{ muscle_group.id }}-title" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="delete-muscle_group-{{ muscle_group.id }}-title">Delete Muscle Group
                {{ MuscleGoup.name }}
              </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to proceed?</p>
              <p><small>The Muscle Group will be delete from all Workouts where it now belongs.</small></p>
              <p>This action can not be undone!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Cancel">Cancel</button>
              <a href="{% url 'delete_muscle_group' muscle_group.id %}">
                <button type="button" class="btn btn-primary" aria-label="Delete Muscle Group">Delete</button>
              </a>
            </div>
          </div>
        </div>
      </div>

      {% empty %}
      <div class="col grid-col2 pt-3">
        <h4>You have no Muscle Groups to show</h4>
      </div>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <div class="jumbotron-head justify-content-center text-center mt-3">
    <h1>Muscle Groups</h1>
    <div class="container-md content-list-container p-sm-4 mt-3 gy-4 dark-clr">
      <div class="row session-workout content-list row-cols-1 pt-3 pb-2">
        <h4>You have to be logged in to see this page</h4>
        <p>Log in <a href="{% url 'login' %}" aria-label="Log in Here">here</a>!</p>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}